# Generated by Django 2.0.7 on 2024-07-10 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierwsza_skladowa', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nazwa',
            field=models.TextField(default='lista zakupow'),
        ),
        migrations.AlterField(
            model_name='lista',
            name='zawartosc',
            field=models.TextField(default=''),
        ),
    ]
