# Generated by Django 2.0.7 on 2024-07-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pierwsza_skladowa', '0002_auto_20240710_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lista',
            name='nazwa',
            field=models.CharField(default='lista zakupow', max_length=40),
        ),
        migrations.AlterField(
            model_name='lista',
            name='zawartosc',
            field=models.CharField(max_length=1000),
        ),
    ]
